include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - build
  - test
  - afterwards

.build_common:
  extends: .dind
  stage: build
  only: ['master', 'develop', 'staging', 'trying']
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t "$IMAGE" --build-arg BUILD_BASE --build-arg DEPLOY_BASE --build-arg SPEC --build-arg ENVIRONMENT -f ci/spack/deploy.Dockerfile --network=host .
    - docker push $IMAGE

cuda_10.1:
  extends: .build_common
  variables:
    SPEC: 'sirius@develop %gcc@7.5.0 build_type=RelWithDebInfo +scalapack +cuda +tests +apps ^cuda@10.1.243 ^openblas ^mpich'
    ENVIRONMENT: ci/spack/cuda-10.yaml
    DEPLOY_BASE: ubuntu:18.04
    BUILD_BASE: stabbles/sirius-cuda-10
    IMAGE: $CI_REGISTRY_IMAGE/cuda_10.1:$CI_COMMIT_SHA

notify_github_start:
  stage: build
  allow_failure: true
  only: ['master', 'develop', 'staging', 'trying']
  tags: ['kubernetes']
  image: stabbles/git-curl
  script: ./ci/set_github_status.sh pending

.run_tests:
  extends: .daint
  stage: test
  only: ['master', 'develop', 'staging', 'trying']
  script: cd /sources/spack-build && $TEST_COMMAND
  variables:
    CRAY_CUDA_MPS: 1
    GIT_STRATEGY: none
    MPICH_MAX_THREAD_SAFETY: multiple
    PULL_IMAGE: 'YES'
    SLURM_EXCLUSIVE: ''
    SLURM_HINT: nomultithread
    SLURM_JOB_NUM_NODES: 1
    SLURM_STDOUTMODE: 0 # only get output from 1 rank

gpu serial:
  extends: .run_tests
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/cuda_10.1:$CI_COMMIT_SHA
    MPICH_MAX_THREAD_SAFETY: multiple
    OMP_NUM_THREADS: 12
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: "20:00"
    TEST_COMMAND: ctest -L gpu_serial -V

gpu band parallel:
  extends: .run_tests
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/cuda_10.1:$CI_COMMIT_SHA
    MPICH_MAX_THREAD_SAFETY: multiple
    OMP_NUM_THREADS: 3
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 3
    SLURM_NTASKS: 4
    SLURM_TIMELIMIT: "20:00"
    TEST_COMMAND: ctest -L gpu_band_parallel -V
    USE_MPI: 'YES'

gpu k-point parallel:
  extends: .run_tests
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/cuda_10.1:$CI_COMMIT_SHA
    MPICH_MAX_THREAD_SAFETY: multiple
    OMP_NUM_THREADS: 3
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 3
    SLURM_NTASKS: 4
    SLURM_TIMELIMIT: "20:00"
    TEST_COMMAND: ctest -L gpu_k_point_parallel -V
    USE_MPI: 'YES'

cpu single:
  extends: .run_tests
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/cuda_10.1:$CI_COMMIT_SHA
    MPICH_MAX_THREAD_SAFETY: multiple
    OMP_NUM_THREADS: 12
    SLURM_CONSTRAINT: gpu
    SLURM_CPU_BIND: sockets
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: "20:00"
    TEST_COMMAND: ctest -L cpu_serial -V

cpu band parallel:
  extends: .run_tests
  variables:
    IMAGE: $CI_REGISTRY_IMAGE/cuda_10.1:$CI_COMMIT_SHA
    MPICH_MAX_THREAD_SAFETY: multiple
    OMP_NUM_THREADS: 3
    SLURM_CONSTRAINT: gpu
    SLURM_CPU_BIND: sockets
    SLURM_CPUS_PER_TASK: 3
    SLURM_NTASKS: 4
    SLURM_TIMELIMIT: "20:00"
    TEST_COMMAND: ctest -L cpu_band_parallel -V
    USE_MPI: 'YES'

notify_github_success:
  stage: afterwards
  when: on_success
  only: ['master', 'develop', 'staging', 'trying']
  tags: ['kubernetes']
  image: stabbles/git-curl
  script: ./ci/set_github_status.sh success

notify_github_failure:
  stage: afterwards
  when: on_failure
  only: ['master', 'develop', 'staging', 'trying']
  tags: ['kubernetes']
  image: stabbles/git-curl
  script: ./ci/set_github_status.sh failure